apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
spec:
  selector:
    app: eks-iam-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: LoadBalancer
