apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-iam-test-node-js
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-iam-test-node-js
  template:
    metadata:
      labels:
        app: eks-iam-test-node-js
    spec:
      serviceAccountName: demo
      containers:
        - name: backend-nodejs
          image: israelbuiatti/awssdk-node:v1
          ports:
            - containerPort: 3333
          imagePullPolicy: "Always"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3333"              
      