apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-iam-test-v2
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-iam-test-v2
  template:
    metadata:
      labels:
        app: eks-iam-test-v2
    spec:
      serviceAccountName: demo
      containers:
        # - name: backend-nodejs
        #   image: israelbuiatti/awssdk-node:v1
        #   command: ["npm"]
        #   args: ["start"]
        #   ports:
        #     - containerPort: 3333
        #   imagePullPolicy: "Always"
        #   env:
        #     - name: NODE_ENV
        #       value: "production"
        #     - name: PORT
        #       value: "3333"              
        - name: backend-java
          image: israelbuiatti/awssdk-java-v2
          ports:
            - containerPort: 8080
          imagePullPolicy: "Always"       
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      