apiVersion: v1
kind: Service
metadata:
  name: demo-service-v2
  namespace: demo
spec:
  selector:
    app: eks-iam-test-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
