version: "3"

services:
  node-aws:
    container_name: node-aws
    build: .
    ports:
      - "3339:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - C:\Users\israe\.aws:/root/.aws:ro      
      