version: '3'
services:
 awssdk-java-v2:
    build: .
    image: israelbuiatti/awssdk-java-v2
    container_name: awssdk-java-v2
    ports:
      - "8081:8083"
    environment:
      - AWS_ROLE_ARN=aws1
      - AWS_WEB_IDENTITY_TOKEN_FILE=aws2
      - AWS_DEFAULT_REGION=us-east-1
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - C:\Users\israe\.aws:/root/.aws:ro
      #- $HOME/.aws:/root/.aws:ro
      #- ~/.aws/:/root/.aws:ro
      