version: '3'
services:
 awssdk-java-v2:
    build: .
    image: israelbuiatti/awssdk-java-v2
    container_name: awssdk-java-v2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - C:\Users\israe\.aws:/root/.aws:ro
      #- $HOME/.aws:/root/.aws:ro
      #- ~/.aws/:/root/.aws:ro
      